name: CI Build

on:
  workflow_dispatch:

env:
  AZURE_WEBAPP_PACKAGE_PATH: publish/bp

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Publish
        run: dotnet publish -c Release --property:PublishDir=${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bp
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
