name: CI with tests

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Install SonarScanner for .NET
      run: |
          dotnet tool install --global dotnet-sonarscanner
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH


    - name: Restore NuGet packages
      run: dotnet restore

    # OWASP DEPENDENCY CHECK (cache + report)
      
    - name: Cache Dependency-Check data
      uses: actions/cache@v4
      with:
          path: ~/.dependency-check
          key: ${{ runner.os }}-dependency-check
          restore-keys: |
            ${{ runner.os }}-dependency-check

    - name: Run OWASP Dependency-Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
          project: "bp"
          path: "."
          format: "HTML"
          out: "dependency-check-report"

    - name: Upload Dependency-Check report
      uses: actions/upload-artifact@v4
      with:
          name: dependency-check-report
          path: dependency-check-report

    - name: SonarCloud - Begin analysis
      env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
           dotnet sonarscanner begin \
            /k:"tud-msc-devops_devops-csfd-ca1-bp-calculator" \
            /o:"tud-msc-devops" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.login="$SONAR_TOKEN" \
            /d:sonar.cs.opencover.reportsPaths="**/TestResults/*/coverage.opencover.xml" \
            /d:sonar.exclusions="**/Program.cs,**/Startup.cs,**/Pages/*.cs,**/Pages/*.cshtml,**/bp-bmi-loadtest.js,**/BPCalculator-E2ETest/**,dependency-check-report/**,**/.github/**,**/*.yml" \
            /d:sonar.test.exclusions="**/BPCalculator-E2ETest/**" \
            /d:sonar.coverage.exclusions="**/Program.cs,**/Startup.cs,**/Pages/*.cs,**/Pages/*.cshtml,**/bp-bmi-loadtest.js,**/BPCalculator-E2ETest/**"

    - name: Build solution (Release)
      run: dotnet build -c Release

    # TEST with coverage (no E2E)
      
    - name: Test with coverage (no E2E)
      run: dotnet test -c Release --no-build --collect:"XPlat Code Coverage;Format=opencover" --logger "trx" --filter "TestCategory!=E2E"

    - name: SonarCloud - End analysis
      env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: dotnet sonarscanner end /d:sonar.login="$SONAR_TOKEN"

    - name: Publish Application
      run: dotnet publish BPCalculator/BPCalculator.csproj -c Release -o ./publish

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: bpapp
        path: ./publish