name: CD Deploy

on:
  workflow_run:
    workflows: ["CI Build"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: bp
          path: ./bp
